apiVersion: v1
kind: Service
metadata:
  name: file-browser-service
  namespace: file-browser-operator-system
spec:
  type: NodePort
  selector:
    control-plane: controller-manager
  ports:
    - protocol: TCP
      port: 8082       # The port that the service will expose
      targetPort: 8082 # The port on the container to route traffic to
      nodePort: 30080 # The port on each node to expose the service (choose an available port in the range 30000-32767)
